const CUSTODY_ACTIONS = {
  REGISTERED: 'REGISTERED',
  ACCESSED: 'ACCESSED',
  TRANSFERRED: 'TRANSFERRED',
  ANALYZED: 'ANALYZED',
  VERIFIED: 'VERIFIED',
  FLAGGED: 'FLAGGED'
};

// Solidity Enum mapping:
// REGISTERED = 0, ACCESSED = 1, TRANSFERRED = 2, ANALYZED = 3, VERIFIED = 4, FLAGGED = 5
const CUSTODY_ACTION_ENUM_MAP = {
  REGISTERED: 0,
  ACCESSED: 1,
  TRANSFERRED: 2,
  ANALYZED: 3,
  VERIFIED: 4,
  FLAGGED: 5
};

const CUSTODY_ACTION_FROM_ENUM = [
  'REGISTERED',
  'ACCESSED',
  'TRANSFERRED',
  'ANALYZED',
  'VERIFIED',
  'FLAGGED'
];

module.exports = {
  CUSTODY_ACTIONS,
  CUSTODY_ACTION_ENUM_MAP,
  CUSTODY_ACTION_FROM_ENUM
};
