const EVIDENCE_STATUS = {
  REGISTERED: 'REGISTERED',
  IN_CUSTODY: 'IN_CUSTODY',
  TRANSFERRED: 'TRANSFERRED',
  UNDER_ANALYSIS: 'UNDER_ANALYSIS',
  VERIFIED: 'VERIFIED',
  FLAGGED: 'FLAGGED',
  ARCHIVED: 'ARCHIVED'
};

const EVIDENCE_CATEGORIES = {
  CCTV_VIDEO: 'CCTV_VIDEO',
  AUDIO_RECORDING: 'AUDIO_RECORDING',
  DIGITAL_IMAGE: 'DIGITAL_IMAGE',
  FORENSIC_DOCUMENT: 'FORENSIC_DOCUMENT',
  DATA_DUMP: 'DATA_DUMP',
  OTHER: 'OTHER'
};

module.exports = {
  EVIDENCE_STATUS,
  EVIDENCE_CATEGORIES
};
